# GitHub Actions Workflow created for handling the release process based on the draft release prepared with the Build workflow.
# Running the publishPlugin task requires all following secrets to be provided: PUBLISH_TOKEN, PRIVATE_KEY, PRIVATE_KEY_PASSWORD, CERTIFICATE_CHAIN.
# See https://plugins.jetbrains.com/docs/intellij/plugin-signing.html for more information.

name: Release Plugin
on:
  release:
    types: [released]

jobs:

  # Prepare and publish the plugin to JetBrains Marketplace repository
  release:
    name: Publish Plugin
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:

      # Free GitHub Actions Environment Disk Space
      - name: Maximize Build Space
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: false
          large-packages: false

      # Check out the current repository
      - name: Fetch Sources
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.release.tag_name }}

      # Set up Java environment for the next steps
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 11

      # Setup Gradle
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-home-cache-cleanup: true

      - name: Grant execute permission for Gradle wrapper
        run: chmod +x ./gradlew

      # Set environment variables
      - name: Export Properties
        id: properties
        shell: bash
        run: |
          PROPERTIES="$(./gradlew properties --console=plain -q)"
          VERSION="$(echo "$PROPERTIES" | grep "^version:" | cut -f2- -d ' ')"
          NAME="$(echo "$PROPERTIES" | grep "^name:" | cut -f2- -d ' ')"
          CHANGELOG="$(cat << 'EOM' | sed -e 's/^[[:space:]]*$//g' -e '/./,$!d'
          ${{ github.event.release.body }}
          EOM
          )"
          
          COMING_NAME="$(echo "$NAME" | sed 's/ /\-/g')"
          
          # 原插件名
          ORIGIN_NAME="$(echo "$PROPERTIES" | grep "^pluginName:" | cut -f2- -d ' ' || echo "$NAME")"
          
          # 混淆映射表
          PROGUARD_MAPPING_FILE_NAME="$ORIGIN_NAME-$VERSION-ProGuard-Mapping.txt"
          
          # 转义空格
          NAME="$(echo "$NAME" | sed 's/ /\\ /g')"
          
          
          echo "name: $NAME"
          echo "coming_name: $COMING_NAME"
          echo "version: $VERSION"
          echo "releaseTagName: ${{ github.event.release.tag_name }}"
          echo "proguardMappingFileName: $PROGUARD_MAPPING_FILE_NAME"
          echo "changelog:"
          echo "$CHANGELOG"
          
          echo "name=$NAME" >> $GITHUB_OUTPUT
          echo "coming_name=$COMING_NAME-$VERSION.zip" >> $GITHUB_OUTPUT
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "pluginName=$NAME-$VERSION.zip" >> $GITHUB_OUTPUT
          echo "pluginSignedName=$NAME-$VERSION-signed.zip" >> $GITHUB_OUTPUT
          echo "proguardMappingFileName=$PROGUARD_MAPPING_FILE_NAME" >> $GITHUB_OUTPUT
          
          echo "changelog<<EOF" >> $GITHUB_OUTPUT
          echo "$CHANGELOG" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      # Update Unreleased section with the current release note
      - name: Patch Changelog
        if: ${{ steps.properties.outputs.changelog != '' }}
        env:
          CHANGELOG: ${{ steps.properties.outputs.changelog }}
        run: |
          ./gradlew patchChangelog --release-note="$CHANGELOG"

      - name: Cat Changelog
        if: ${{ steps.properties.outputs.changelog != '' }}
        run: |
          cat ./CHANGELOG.md

      # Publish the plugin to JetBrains Marketplace
      - name: Publish Plugin
        env:
          PUBLISH_TOKEN: ${{ secrets.PUBLISH_TOKEN }}
          CERTIFICATE_CHAIN: ${{ secrets.CERTIFICATE_CHAIN }}
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          PRIVATE_KEY_PASSWORD: ${{ secrets.PRIVATE_KEY_PASSWORD }}
#          RELEASE_MODE: "true" # 设置发布标识
        run: ./gradlew publishPlugin

#      # 上传保存混淆映射文件（重要，因为每次混淆的类名都可能不一样）
#      - name: Upload Obfuscation Mapping
#        uses: actions/upload-artifact@v4
#        with:
#          name: Obfuscation-Mapping
#          path: ./build/obfuscated/output/${{ steps.properties.outputs.proguardMappingFileName }}
#          retention-days: 60  # 60天后自动删除

#      - name: Upload WebDAV
#        uses: bxb100/action-upload-webdav@v0.0.6
#        with:
#          webdav_address: ${{ secrets.WEBDAV_ADDRESS }}
#          webdav_username: ${{ secrets.WEBDAV_USERNAME }}
#          webdav_password: ${{ secrets.WEBDAV_PASSWORD }}
#          webdav_upload_path: "/Plugins/Json-Assistant/ProGuard"
#          files: "./build/obfuscated/output/${{ steps.properties.outputs.proguardMappingFileName }}"

      - name: Move zip
        run: |
          echo "${{ steps.properties.outputs.pluginName }}"
          echo "${{ steps.properties.outputs.pluginSignedName }}"
          
          # 移除原本未签名的压缩包
          mkdir test
          mv ./build/distributions/${{ steps.properties.outputs.pluginName }} test/${{ steps.properties.outputs.pluginName }}

          echo "已移除未签名压缩包，查看文件："
          echo "/build/distributions："
          ls ./build/distributions
          echo "/test："
          ls ./test

          mv ./build/distributions/${{ steps.properties.outputs.pluginSignedName }} ./build/distributions/${{ steps.properties.outputs.coming_name }}

          echo "已将签名压缩包更名，查看文件："
          echo "/build/distributions："
          ls ./build/distributions
          echo "/test："
          ls ./test

      # Upload artifact as a release asset
      - name: Upload Release Asset
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release upload ${{ github.event.release.tag_name }} ./build/distributions/${{ steps.properties.outputs.coming_name }}

      # 同步发布目标仓库的草稿Release
#      - name: Publish Draft in Target Repository
#        env:
#          GH_TOKEN: ${{ secrets.TARGET_TOKEN }}  # 目标仓库PAT
#          TARGET_REPO: "${{ github.repository_owner }}/Json-Assistant"
#          RELEASE_TAG: "${{ github.event.release.tag_name }}"
#        run: |
#          gh release edit "$RELEASE_TAG" \
#          --draft=false \
#          --repo "$TARGET_REPO"

      # 上传到目标仓库的Release
#      - name: Upload to Target Repository Release
#        env:
#          GH_TOKEN: ${{ secrets.TARGET_TOKEN }}  # 目标仓库PAT
#          TARGET_REPO: "${{ github.repository_owner }}/Json-Assistant"
#          RELEASE_TAG: "${{ github.event.release.tag_name }}"
#          FILE_PATH: ./build/distributions/${{ steps.properties.outputs.coming_name }}
#        run: |
#          echo "⬆️ Uploading to target repository: $TARGET_REPO"
#
#          gh release upload $RELEASE_TAG \
#            $FILE_PATH \
#            -R $TARGET_REPO \
#            --clobber  # 覆盖已存在文件
#
#          echo "✅ Assets uploaded to target repository"

      # 删除新标签分支
      - name: Check If Branch Exists
        run: |
          VERSION="${{ github.event.release.tag_name }}"
          BRANCH="changelog-update-$VERSION"
          
          echo "branch_name=$BRANCH" >> $GITHUB_ENV
          
          if git ls-remote --exit-code --heads origin "$BRANCH"; then
            echo "[$BRANCH] 分支存在"
            echo "branch_exists=true" >> $GITHUB_ENV
          else
            echo "[$BRANCH] 分支不存在"
            echo "branch_exists=false" >> $GITHUB_ENV
          fi

      - name: Delete Branch If Exists
        if: env.branch_exists == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          branch="${{ env.branch_name }}"
          git push origin --delete "$branch"
          

      # Create a pull request
      - name: Create Pull Request
        if: ${{ steps.properties.outputs.changelog != '' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          VERSION="${{ github.event.release.tag_name }}"
          BRANCH="changelog-update-$VERSION"
          LABEL="release changelog"

          git config user.email "action@github.com"
          git config user.name "GitHub Action"

          git checkout -b $BRANCH
          git commit -am "Changelog update - $VERSION"
          git push --set-upstream origin $BRANCH
          
          gh label create "$LABEL" \
            --description "Pull requests with release changelog update" \
            --force \
            || true

          gh pr create \
            --title "Changelog update - \`$VERSION\`" \
            --body "Current pull request contains patched \`CHANGELOG.md\` file for the \`$VERSION\` version." \
            --label "$LABEL" \
            --head $BRANCH
